# https://circleci.com/docs/2.0/language-java-maven/
version: 2
jobs:
  build:
    working_directory: ~/sample-spring-hateoas-hal-forms
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: sample-spring-hateoas-hal-forms-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline      
      - save_cache:
          paths:
            - ~/.m2
          key: sample-spring-hateoas-hal-forms-{{ checksum "pom.xml" }}
      - run: mvn verify -B
      - store_test_results: 
          path: target/surefire-reports
      - store_artifacts:
          path: target/spring-hateoas-hal-forms-1.0.0-SNAPSHOT.jar
